export const KAFKA_CONSUMER_SERVICE = 'MICROSERVICE_REQUEST_SERVICE';
export const KAFKA_PRODUCER_SERVICE = 'MICROSERVICE_RESPONSE_SERVICE';

export const KAFKA_CONSUMER_GROUP_ID = 'microservice-consumer';
